### ISSUE TITLE
Add Contributors

### ISSUE THREAD

**Issue by Sanketwable** [Sachinwattamwar/Blog-Website#2]
@all-contributors please add @Sachinwattamwar for design

**Comment by Sanketwable** [comment]
@all-contributors please add @sanketnagrale for blog

**Comment by Sachinwattamwar** [comment]
@all-contributors please add @Sachinwattamwar for design

**Comment by Sachinwattamwar** [comment]
@all-contributors please add @sanketnagrale for blog

**Comment by Sachinwattamwar** [comment]
@all-contributors please add @Sachinwattamwar for backend and authentication.

**Comment by Sachinwattamwar** [comment]
Done
